export class LogisticCenterEntity {
  public Id: number = 0;
  public CA: string;
  public CABreve: string;
  public RagioneSociale: string;
  public Indirizzo: string;
  public Localita: string;
  public Provincia: string;
  public CAP: string;
  public Stato: string;
  public Telefono: string;
  public KMEfeso: string;
  public P1: number = 0;
  public P2: number = 0;
  public P3: number = 0;
  public TG1: number = 0;
  public TG2: number = 0;
  public TG3: number = 0;
  public TG4: number = 0;
  public PRifPieni: number = 0;
  public Attivo: string;
  public PVLSerieNew: string;
  public PVLSerieManuale: string;
  public PVLSerieCarico: string;
  public PVLSerieBolla: string;
  public SOCART: string;
  public OnlyCMR: boolean = false;
  public CompanyNameFirstClient: boolean = false;
  public LuogoCA: string;
  public UseAutoDemand: boolean = false;
  public AbilitaViaggiManuali: boolean = false;
  public AbilitaInserimentoRapidoViaggi: boolean = false;
  public PassaggioManualeFatturazione: boolean = false;
  public AnnullamentoPVLDefinitivo: string;
  public AutoConfirm: string;
  public AutoConfirmPerc: number = 0;
  public AutoConfirmValue: number = 0;
  public AbilitaStampa: number = 0;
  public MandatoryLotsData: boolean = false;
  public BlockingCompaniesCheck: boolean = false;
  public Responsibles: string;
  public notforas: boolean = false;
  public usemanualddt: boolean = false;
  public manualddtseries: string;
  public TravelGrant: string;
  public AllowReloadPointEdit: boolean = false;
  public HiddenExternalLoadingPoint: boolean = false;
  public AnomaliesMaxPhotoNr: number = 0;
  public RoadTankPrefix: string;

}
